### ISSUE TITLE
Prediction file of wikisql data

### ISSUE THREAD

**Issue by Nayan-Das** [shmsw25/qa-hard-em#15]
Hi,

Would it be possible for you to add a prediction file to run the prediction on WikiSQL dataset using your pre-trained model?

Thanks,
nayan

**Comment by shmsw25** [comment]
Sure, here it is! [[Google drive link](https://drive.google.com/file/d/1hAO0f5rbzGI9j2W6MznUW3dWdwCwWNde/view?usp=sharing)]

**Comment by Nayan-Das** [comment]
Thank you for your response. But I was asking for prediction.py file which can be used to predict SQL query from a question.

**Comment by shmsw25** [comment]
Oh got it, sorry I misunderstood.

I created [another branch](https://github.com/shmsw25/qa-hard-em/tree/wikisql) called `wikisql` for the codes for training and testing WikiSQL. These codes are largely adapted by [SQLova codes](https://github.com/naver/sqlova). We use their model as a base model, as described in the paper. We only made marginal modifications (to adjust the memory usage, etc) and the learning objective to use Hard EM or MML instead of using the strong supervision from WikiSQL annotations (implementations of these objectives are [here](https://github.com/shmsw25/qa-hard-em/blob/wikisql/train.py#L344)).

To come back to your original question on how to make a prediction, please do the following.

1. For the setup, follow README or [the original SQLova repo](https://github.com/naver/sqlova).
2. Download [BERT base](https://drive.google.com/file/d/1XaMX-u5ZkWGH3f0gPrDtrBK1lKDU-QFk/view?usp=sharing) and [pretrained SQLova model](https://drive.google.com/file/d/13v7-YfmuXcHyi_QXAo47ShjNK1yZlH2m/view?usp=sharing). Note that if you use the preatrined SQLova model, the initial BERT base checkpoint is not required but we still use the config and vocab of them. Place both of them in the same directory as the code and unzip them.
3. Run the following to make predictions.
```
python3 train.py --seed 1 --bert_type_abb uS --finetune --path_wikisql {path_to_wikisql_data} --path_out `hard-em` --max_seq_length 180 --bS 40 --test {dev|test} --trained
```
Note that running `train.py` with `--trained` will load the pretrained model, and specifying `--test` will do the testing instead of training. This script will save the prediction in `out/hard-em/results_{dev|test}_final.json` which are comparable to the official WikiSQL evaluation script.

Hope this helps, and let me know if you run into any problems.
