### ISSUE TITLE
answers may not totally match a substring of question

### ISSUE THREAD

**Issue by chen1234yue** [shmsw25/qa-hard-em#2]
After reading the readme, it seems that start and end span of answers in context must exist in training data. Could we use your method to solve problems that answers may not totally match a substring of question. Do we need to calculate the start and end span which get max rouge-l score.

**Comment by shmsw25** [comment]
Hi @chen1234yue, thanks for your interest. Yes, the current code is for open-domain QA where we only considered the answer span which exactly matches the answer text. However, when we experimented on NarrativeQA, we considered all spans that has the max rouge-l score.
[Link](https://drive.google.com/file/d/1D_cVeY6Y6soxhHwbFuc5oIca8ZsEnRg7/view?usp=sharing) Here is the code for that, in case it will be helpful. (It converts NarrativeQA into SQuAD format so not exactly comparable with the code in the repo.) You will need to install [ROUGE package](https://github.com/pltrdy/rouge) in order to run this code.

**Comment by chen1234yue** [comment]
OK. Thank you so much.
